import {
  type Plugins,
  // Component type plugins
  textFieldPlugin,
  booleanFieldPlugin,
  contentPlugin,
  emailFieldPlugin,
  fileFieldPlugin,
  groupPlugin,
  integerFieldPlugin,
  floatFieldPlugin,
  pageBreakPlugin,
  urlFieldPlugin,
  // Widget plugins
  textFieldWidgetPlugin,
  textAreaWidgetPlugin,
  checkboxWidgetPlugin,
  contentWidgetPlugin,
  emailFieldWidgetPlugin,
  fileUploadWidgetPlugin,
  groupWidgetPlugin,
  horizontalGroupWidgetPlugin,
  fieldsetWidgetPlugin,
  detailsWidgetPlugin,
  numberFieldWidgetPlugin,
  pageBreakWidgetPlugin,
  linkFieldWidgetPlugin,
  radiosWidgetPlugin,
  selectWidgetPlugin,
  // Validator plugins
  existsValidatorPlugin,
  minLengthValidatorPlugin,
  maxLengthValidatorPlugin,
  minValidatorPlugin,
  maxValidatorPlugin,
  allowedValuesValidatorPlugin,
  disallowedValuesValidatorPlugin,
} from "@fab4m/builder";

// Keep plugins local to docs examples so we only include widgets that work with
// the base @fab4m/react renderer.
export const formBuilderPlugins: Plugins = {
  types: [
    textFieldPlugin,
    booleanFieldPlugin,
    contentPlugin,
    emailFieldPlugin,
    fileFieldPlugin,
    groupPlugin,
    integerFieldPlugin,
    floatFieldPlugin,
    pageBreakPlugin,
    urlFieldPlugin,
  ],
  widgets: [
    textFieldWidgetPlugin,
    textAreaWidgetPlugin,
    checkboxWidgetPlugin,
    contentWidgetPlugin,
    emailFieldWidgetPlugin,
    fileUploadWidgetPlugin,
    groupWidgetPlugin,
    horizontalGroupWidgetPlugin,
    fieldsetWidgetPlugin,
    detailsWidgetPlugin,
    numberFieldWidgetPlugin,
    pageBreakWidgetPlugin,
    linkFieldWidgetPlugin,
    radiosWidgetPlugin,
    selectWidgetPlugin,
  ],
  validators: [
    existsValidatorPlugin,
    minLengthValidatorPlugin,
    maxLengthValidatorPlugin,
    minValidatorPlugin,
    maxValidatorPlugin,
    allowedValuesValidatorPlugin,
    disallowedValuesValidatorPlugin,
  ],
};
